version: '3.8'

services:
  food-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-store-app
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend API
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEXT_PORT=3000
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - UPI_ID=your-upi-id@paytm
      - BUSINESS_NAME=Food Store
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - food_store_data:/app/server/data
      - food_store_uploads:/app/server/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  food_store_data:
    driver: local
  food_store_uploads:
    driver: local

networks:
  default:
    name: food-store-network
